default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: techlog_app
  username: techlog_app_user
  password: kyeZxobywxwtGeHnUaveRMX6cvpK3PSc

test:
  <<: *default
  database: techlog_app
  username: techlog_app_user
  password: kyeZxobywxwtGeHnUaveRMX6cvpK3PSc

production:
  <<: *default
  database: techlog_app
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
