default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 20250128
  host: 127.0.0.1
  port: 5432
development:
  <<: *default
  database: techlog_app

test:
  <<: *default
  database: techlog_app

production:
  <<: *default
  database: techlog_app
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
